export const thinking = [
  {
    id: 1,
    point: 'POINT OF VIEW',
    bullet1: 'All thinking takes place from a particular perspective.',
    bullet2: 'What is the point of view?',
    bullet3: 'What other points of view should be considered in reasoning through the problem?',
    bullet4: '',
  },
  {
    id: 2,
    point: 'PURPOSE',
    bullet1: 'The part of thinking that includes defining a goal or objective of the topic.',
    bullet2: 'What is the purpose of the goal, the objective, what is it trying to accomplish?',
    bullet3: 'Why is this it being developed?',
    bullet4: '',
  },
  {
    id: 3,
    point: 'QUESTIONS',
    bullet1: 'The part that includes the attempts that previously addressed the topic or attempts to solve a problem.',
    bullet2: 'What is the problem being presented or addressed?',
    bullet3: '',
    bullet4: '',
  },
  {
    id: 4,
    point: 'ASSUMPTIONS',
    bullet1: 'The part that is a presupposition that helps shape the point of view. Assumptions may be true or false, justified or unjustified.',
    bullet2: 'What is taking for granted?',
    bullet3: 'Is it assuming something it shouldn’t?',
    bullet4: 'What assumption is leading to this conclusion?',
  },
  {
    id: 5,
    point: 'CONSEQUENCES',
    bullet1: 'All the reasons must lead to consequences that are a result of implementing the results of the reasoning process.',
    bullet2: 'What are the implications of the proposed solution?',
    bullet3: 'If it is decided to do / not to do “Something”, what might happen?',
    bullet4: 'What is likely to happen if it did this versus that?',
  },
  {
    id: 6,
  point: 'INFORMATION',
    bullet1: 'It covers the data and information related to the topic. Also, have all the evidence that supports the topic.',
    bullet2: 'What information is needed to answer the question?',
    bullet3: 'What information you have and what information you do not have, but need?',
    bullet4: 'What previous experiences can you draw from?',
  },
  {
    id: 7,
   point: 'CONCEPTS',
    bullet1: 'It applies "theories, principles, axioms and rules" that guide the thinking.',
    bullet2: 'What concepts will it use to correct the problem?',
    bullet3: 'Are there any theories or laws at play?',
    bullet4: '',
  },
  {
    id: 8,
    point: 'CONCLUSION',
    bullet1: 'It may include the suggested solution of a specific problem.',
    bullet2: 'What are the judgments that will allow the user to know if it has been successful?',
    bullet3: '',
    bullet4: '',
  },
  
];
